# This configuration file is for a rotary encoder that adjusts the flywheel resistance on a ride kit.
# It uses a PCA9685 PWM controller to control the servo that adjusts the resistance.
sensor:
  - platform: rotary_encoder
    name: "Flywheel Resistance Adjuster"
    id: resistance_encoder
    pin_a: ${flywheel_resistance_rotary_encoder_a_pin}
    pin_b: ${flywheel_resistance_rotary_encoder_b_pin}
    min_value: 0
    max_value: 50  # You can adjust this range based on servo resolution
    resolution: 1
    on_value:
      then:
        - logger.log:
            format: "Encoder value changed: %d"
            args: [ 'id(resistance_encoder).state' ]
        - lambda: |-
            float level = id(resistance_encoder).state / 50.0;
            id(flywheel_resistance_servo).write(level);
            id(flywheel_resistance_slider).publish_state(level);
            
  - platform: template
    name: "Rotary Encoder Resistance (%)"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    lambda: |-
      return round((id(resistance_encoder).state / 50.0) * 100.0);
    update_interval: 250ms