esphome:
  name: ridekit
  friendly_name: RideKit Exercise Bike

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Allow Over-The-Air updates
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable BLE for future HR monitor support (optional for now)
esp32_ble_tracker:

# Substitutions for pin management and easy reuse
substitutions:
  resistance_servo_pin: GPIO18
  cadence_sensor_pin: GPIO14
  up_button_pin: GPIO12
  down_button_pin: GPIO13
  encoder_a_pin: GPIO25
  encoder_b_pin: GPIO26
  encoder_button_pin: GPIO27

# Modular includes — create these files as your project grows
packages:
  pwm: !include ridekit/control/pwm_controller.yaml
  flywheel: !include ridekit/control/flywheel_resistance_servo.yaml
  encoder: !include ridekit/inputs/flywheel_resistance_rotary_encoder.yaml
  sensors: !include ridekit/sensors/cadence.yaml
  inputs: !include ridekit/inputs/buttons.yaml
  display: !include ridekit/display/screen.yaml
  


